server:
  port: 83


spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

feign:
  httpclient:
    connection-timeout: 5000
    connection-timer-repeat: 5000